[project]
name = "trustpilotscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scrapy>=2.13.4",
    "scrapy-fake-useragent>=1.4.4",
]
